### ISSUE TITLE
Build errors when updating to 0.5

### ISSUE THREAD

**Issue by sin2** [QuickBlox/q-municate-services-ios#335]
Use of undeclared identifier 'QMServicesManager'

Also I cannot revert back to 0.4.6.

**Comment by sin2** [comment]
Had to update import statements

**Before**
```
#import "QMServices.h"
```
**After**
```
#import <QMServices/QMServicesManager.h>
#import <QMServices/QMServices.h>
```
